#modLoader="javafml" #mandatory #default
#loaderVersion="[47,)" #mandatory #default
modLoader="kotlinforforge" #mandatory #with-kotlin-for-forge
loaderVersion="[3,)" #mandatory #with-kotlin-for-forge
license="Mozilla Public License 2.0"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="cobblemontournament" #mandatory
version="${version}" #mandatory
displayName="Cobblemon Tournament" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="icon.png" #optional
credits="Thank you TurtleHoarder for putting up with my endless stream of questions!" #optional
authors="Eight" #optional
# MATCH_VERSION | IGNORE_SERVER_VERSION | IGNORE_ALL_VERSION | NONE
displayTest="MATCH_VERSION" #optional #MATCH_VERSION is the default if nothing is specified
#mandatory # !! multi line !!
description='''

'''
#dependencies #optional
[[dependencies.cobblemontournament]] #optional
    modId="forge" #mandatory #the modid of the dependency
    mandatory=true #mandatory # Does this dependency have to exist - if not, ordering below must be specified
    versionRange="[47,)" #mandatory # The version range of the dependency
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies.cobblemontournament]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.20.1,1.21)" #mandatory
    ordering="NONE"
    side="BOTH"